activities:
    move_default: 1.0
    load_default: 8.0
    unload_default: 8.0
    install_default: 14.0
    transfer_default: 3.0
    move_matrix:
        fabrication_yard:
            marshalling_yard: 240.0
            installation_site: 288.0
        marshalling_yard:
            fabrication_yard: 240.0
            installation_site: 96.0
        installation_site:
            fabrication_yard: 288.0
            marshalling_yard: 96.0
    installations:
        Bokalift: # Bokalift installs to installation site and it takes n hours
            installation_site: 14.0
