activities:
    move_default: 1.0
    load_default: 4.0
    unload_default: 4.0
    install_default: 14.0
    transfer_default: 3.0
    move_matrix:
        fabrication_yard:
            marshalling_yard: 60.0
            installation_site: 70.0
        marshalling_yard:
            fabrication_yard: 60.0
            installation_site: 15.0
        installation_site:
            fabrication_yard: 70.0
            marshalling_yard: 15.0
    installations:
        installation_vessel: # installation_vessel installs to installation site and it takes n hours
            installation_site: 40.0
