defaults:
    - objects@_here_: barge
    - inventory@_here_: scenario_a
    - goals@_here_: scenario_a
    - activities@_here_: marshalling_close
    - install_windows@_here_: none

use_business_rules: false
