resource_types:
    monopile:
        quantity: 2

sites:
    installation_site:
        resource_types:
            monopile:
                capacity: 2
        total_capacity: 2

vessels:
    HTV:
        resource_types:
            monopile:
                capacity: 2
        initial_levels:
            monopile: 2
        total_capacity: 2

    installation_vessel:
        resource_types:
            monopile:
                capacity: 1
        total_capacity: 1
